export type AnalysisExportLanguage = "English" | "Turkish";

type EvidenceItem = {
  requirement: string;
  jobEvidence: string;
  cvEvidence: string;
  explanation: string;
};

type PartialMatchItem = EvidenceItem & {
  remainingGap: string;
};

type LearnableGapItem = {
  skill: string;
  jobEvidence: string;
  cvEvidence: string;
  importance: string;
  suggestion: string;
};

type BlockerItem = {
  requirement: string;
  jobEvidence: string;
  cvEvidence: string;
  reason: string;
  severity: string;
};

type CvSuggestionItem = {
  section: string;
  suggestion: string;
  reason: string;
  example: string;
};

export type AnalysisExportInput = {
  jobTitle: string;
  companyName: string;
  jobUrl?: string;
  language: AnalysisExportLanguage;
  analysis: {
    verdict: string;
    verdictExplanation: string;
    matchScore: number;
    strongMatches: EvidenceItem[];
    partialMatches: PartialMatchItem[];
    learnableGaps: LearnableGapItem[];
    possibleBlockers: BlockerItem[];
    cvSuggestions: CvSuggestionItem[];
    recruiterMessage: string;
    disclaimer: string;
  };
  decisionBrief?: {
    evidenceStrengthLabel: string;
    mainRisk: string;
    bestNextMove: string;
    recruiterPerspective: string;
  } | null;
  careerDirection?: {
    label: string;
    score: number | null;
  };
};

function clean(value: string | undefined): string {
  return value?.trim() ?? "";
}

function bullet(value: string): string {
  return `- ${value}`;
}

export function buildAnalysisShareSummary(
  input: AnalysisExportInput,
): string {
  const tr = input.language === "Turkish";
  const company = clean(input.companyName);

  const lines = [
    "JobLens AI",
    "",
    `${tr ? "Rol" : "Role"}: ${clean(input.jobTitle)}`,
    ...(company
      ? [`${tr ? "Şirket" : "Company"}: ${company}`]
      : []),
    `${tr ? "Uyum skoru" : "Match score"}: ${input.analysis.matchScore}/100`,
    `${tr ? "Sonuç" : "Verdict"}: ${input.analysis.verdict}`,
    "",
    input.analysis.verdictExplanation,
  ];

  if (input.decisionBrief) {
    lines.push(
      "",
      `${tr ? "Ana risk" : "Main risk"}: ${input.decisionBrief.mainRisk}`,
      `${tr ? "En iyi sonraki adım" : "Best next move"}: ${input.decisionBrief.bestNextMove}`,
    );
  }

  if (input.careerDirection?.label) {
    lines.push(
      "",
      `${tr ? "Kariyer yönü" : "Career direction"}: ${input.careerDirection.label}${
        input.careerDirection.score !== null
          ? ` (${input.careerDirection.score}%)`
          : ""
      }`,
    );
  }

  lines.push(
    "",
    tr
      ? "JobLens AI tarafından oluşturulan açıklanabilir bir tahmindir; resmi bir işe alım kararı değildir."
      : "Generated by JobLens AI as an explainable estimate, not an official hiring decision.",
  );

  return lines.join("\n");
}

export function buildAnalysisExportText(
  input: AnalysisExportInput,
): string {
  const tr = input.language === "Turkish";
  const company = clean(input.companyName);

  const lines: string[] = [
    "JOBLENS AI — APPLICATION ANALYSIS",
    "=================================",
    "",
    `${tr ? "Rol" : "Role"}: ${clean(input.jobTitle)}`,
    ...(company
      ? [`${tr ? "Şirket" : "Company"}: ${company}`]
      : []),
    ...(clean(input.jobUrl)
      ? [`${tr ? "İlan" : "Job URL"}: ${clean(input.jobUrl)}`]
      : []),
    `${tr ? "Uyum skoru" : "Match score"}: ${input.analysis.matchScore}/100`,
    `${tr ? "Sonuç" : "Verdict"}: ${input.analysis.verdict}`,
    "",
    input.analysis.verdictExplanation,
  ];

  if (input.decisionBrief) {
    lines.push(
      "",
      tr ? "KARAR ÖZETİ" : "DECISION BRIEF",
      "------------------------------",
      `${tr ? "Kanıt gücü" : "Evidence strength"}: ${input.decisionBrief.evidenceStrengthLabel}`,
      `${tr ? "Ana risk" : "Main risk"}: ${input.decisionBrief.mainRisk}`,
      `${tr ? "En iyi sonraki adım" : "Best next move"}: ${input.decisionBrief.bestNextMove}`,
      `${tr ? "İşe alım perspektifi" : "Recruiter perspective"}: ${input.decisionBrief.recruiterPerspective}`,
    );
  }

  if (input.careerDirection?.label) {
    lines.push(
      "",
      tr ? "KARİYER YÖNÜ" : "CAREER DIRECTION",
      "------------------------------",
      `${input.careerDirection.label}${
        input.careerDirection.score !== null
          ? ` — ${input.careerDirection.score}%`
          : ""
      }`,
    );
  }

  lines.push(
    "",
    tr ? "GÜÇLÜ EŞLEŞMELER" : "STRONG MATCHES",
    "------------------------------",
  );

  if (input.analysis.strongMatches.length === 0) {
    lines.push(tr ? "- Yok" : "- None");
  } else {
    for (const item of input.analysis.strongMatches) {
      lines.push(
        bullet(item.requirement),
        `  ${tr ? "İlan kanıtı" : "Job evidence"}: ${item.jobEvidence}`,
        `  ${tr ? "CV kanıtı" : "CV evidence"}: ${item.cvEvidence}`,
        `  ${item.explanation}`,
        "",
      );
    }
  }

  lines.push(
    "",
    tr ? "KISMİ EŞLEŞMELER" : "PARTIAL MATCHES",
    "------------------------------",
  );

  if (input.analysis.partialMatches.length === 0) {
    lines.push(tr ? "- Yok" : "- None");
  } else {
    for (const item of input.analysis.partialMatches) {
      lines.push(
        bullet(item.requirement),
        `  ${tr ? "İlan kanıtı" : "Job evidence"}: ${item.jobEvidence}`,
        `  ${tr ? "CV kanıtı" : "CV evidence"}: ${item.cvEvidence}`,
        `  ${tr ? "Eksik kalan" : "Remaining gap"}: ${item.remainingGap}`,
        `  ${item.explanation}`,
        "",
      );
    }
  }

  lines.push(
    "",
    tr ? "GELİŞTİRİLEBİLİR EKSİKLER" : "LEARNABLE GAPS",
    "------------------------------",
  );

  if (input.analysis.learnableGaps.length === 0) {
    lines.push(tr ? "- Yok" : "- None");
  } else {
    for (const item of input.analysis.learnableGaps) {
      lines.push(
        bullet(`${item.skill} — ${item.importance}`),
        `  ${tr ? "İlan kanıtı" : "Job evidence"}: ${item.jobEvidence}`,
        `  ${tr ? "CV kanıtı" : "CV evidence"}: ${item.cvEvidence}`,
        `  ${tr ? "Öneri" : "Suggestion"}: ${item.suggestion}`,
        "",
      );
    }
  }

  lines.push(
    "",
    tr ? "OLASI ENGELLER" : "POSSIBLE BLOCKERS",
    "------------------------------",
  );

  if (input.analysis.possibleBlockers.length === 0) {
    lines.push(tr ? "- Yok" : "- None");
  } else {
    for (const item of input.analysis.possibleBlockers) {
      lines.push(
        bullet(`${item.requirement} — ${item.severity}`),
        `  ${tr ? "İlan kanıtı" : "Job evidence"}: ${item.jobEvidence}`,
        `  ${tr ? "CV kanıtı" : "CV evidence"}: ${item.cvEvidence}`,
        `  ${tr ? "Neden" : "Reason"}: ${item.reason}`,
        "",
      );
    }
  }

  lines.push(
    "",
    tr ? "CV GELİŞTİRME ÖNERİLERİ" : "CV IMPROVEMENT SUGGESTIONS",
    "------------------------------",
  );

  if (input.analysis.cvSuggestions.length === 0) {
    lines.push(tr ? "- Yok" : "- None");
  } else {
    for (const item of input.analysis.cvSuggestions) {
      lines.push(
        bullet(item.section),
        `  ${tr ? "Öneri" : "Suggestion"}: ${item.suggestion}`,
        `  ${tr ? "Neden" : "Why"}: ${item.reason}`,
        ...(clean(item.example)
          ? [
              `  ${tr ? "Örnek düzenleme" : "Example rewrite"}: ${item.example}`,
            ]
          : []),
        "",
      );
    }
  }

  lines.push(
    "",
    tr ? "İŞE ALIM UZMANINA MESAJ" : "RECRUITER MESSAGE",
    "------------------------------",
    input.analysis.recruiterMessage,
    "",
    tr ? "NOT" : "NOTE",
    "------------------------------",
    input.analysis.disclaimer,
    "",
    "JobLens AI · https://www.getjoblensai.com",
  );

  return lines.join("\n");
}

export function buildAnalysisExportFilename(
  input: AnalysisExportInput,
): string {
  const raw = [
    input.companyName,
    input.jobTitle,
    "JobLens",
  ]
    .filter(Boolean)
    .join("-")
    .toLowerCase();

  const safe =
    raw
      .normalize("NFKD")
      .replace(/[^\w\s-]/g, "")
      .replace(/[\s_]+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "") || "joblens-analysis";

  return `${safe}.txt`;
}
