import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteNav } from "@/components/SiteNav";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — JobLens AI" },
      {
        name: "description",
        content: "Terms of Service for JobLens AI.",
      },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <SiteNav />

      <main className="mx-auto max-w-3xl px-6 py-16">
        <Link
          to="/"
          className="text-sm text-muted-foreground hover:text-foreground"
        >
          ← Back to JobLens AI
        </Link>

        <h1 className="mt-8 text-4xl font-semibold tracking-tight">
          Terms of Service
        </h1>

        <p className="mt-3 text-sm text-muted-foreground">
          Last updated: August 20, 2026
        </p>

        <div className="mt-10 space-y-8 leading-7 text-muted-foreground">
          <section>
            <h2 className="text-xl font-semibold text-foreground">
              1. About JobLens AI
            </h2>
            <p className="mt-3">
              JobLens AI provides tools for job-fit analysis, application
              tracking, recruitment email signal detection, and related
              career-support features.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              2. AI-generated information
            </h2>
            <p className="mt-3">
              AI-generated analysis is provided for informational and
              educational purposes. Match scores, recommendations, and other
              outputs are estimates and are not official hiring, recruiter, or
              applicant-tracking-system decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              3. Your responsibility
            </h2>
            <p className="mt-3">
              You are responsible for reviewing information generated by
              JobLens AI before relying on it for career or application
              decisions and for ensuring that information you submit is lawful
              and accurate.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              4. Google and Gmail features
            </h2>
            <p className="mt-3">
              Gmail integration is optional and uses read-only access. JobLens
              AI may identify possible recruitment-related emails, but you
              remain in control of whether a detected signal is linked to or
              used to update an application.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              5. Availability
            </h2>
            <p className="mt-3">
              JobLens AI may be changed, improved, suspended, or discontinued
              at any time. Features may also depend on third-party services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              6. Limitation of liability
            </h2>
            <p className="mt-3">
              JobLens AI does not guarantee employment outcomes, interviews,
              offers, or the accuracy of third-party recruitment information.
              Use of the service is at your own discretion.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              7. Changes to these terms
            </h2>
            <p className="mt-3">
              These Terms may be updated as the product evolves. The latest
              version will be available on this page.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
