/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiInterviewPrepRouteImport } from './routes/api/interview-prep'
import { Route as ApiJobImportRouteImport } from './routes/api/job-import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewPrepRoute = ApiInterviewPrepRouteImport.update({
  id: '/api/interview-prep',
  path: '/api/interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobImportRoute = ApiJobImportRouteImport.update({
  id: '/api/job-import',
  path: '/api/job-import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/interview-prep': typeof ApiInterviewPrepRoute
  '/api/job-import': typeof ApiJobImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/interview-prep': typeof ApiInterviewPrepRoute
  '/api/job-import': typeof ApiJobImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/interview-prep': typeof ApiInterviewPrepRoute
  '/api/job-import': typeof ApiJobImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/goals'
    | '/privacy'
    | '/terms'
    | '/api/analyze'
    | '/api/interview-prep'
    | '/api/job-import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/goals'
    | '/privacy'
    | '/terms'
    | '/api/analyze'
    | '/api/interview-prep'
    | '/api/job-import'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/dashboard'
    | '/goals'
    | '/privacy'
    | '/terms'
    | '/api/analyze'
    | '/api/interview-prep'
    | '/api/job-import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  GoalsRoute: typeof GoalsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiInterviewPrepRoute: typeof ApiInterviewPrepRoute
  ApiJobImportRoute: typeof ApiJobImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview-prep': {
      id: '/api/interview-prep'
      path: '/api/interview-prep'
      fullPath: '/api/interview-prep'
      preLoaderRoute: typeof ApiInterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/job-import': {
      id: '/api/job-import'
      path: '/api/job-import'
      fullPath: '/api/job-import'
      preLoaderRoute: typeof ApiJobImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  GoalsRoute: GoalsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiInterviewPrepRoute: ApiInterviewPrepRoute,
  ApiJobImportRoute: ApiJobImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
